---
- type: replace
  path: /instance_groups/name=windows1803-cell/jobs/name=metrics-agent-windows?
  value:
    name: metrics-agent-windows
    release: metrics-discovery
    properties:
      grpc:
        ca_cert: "((loggregator_tls_agent.ca))"
        cert: "((loggregator_tls_agent.certificate))"
        key: "((loggregator_tls_agent.private_key))"
      metrics:
        ca_cert: "((metrics_agent_tls.ca))"
        cert: "((metrics_agent_tls.certificate))"
        key: "((metrics_agent_tls.private_key))"
        server_name: metrics_agent
      scrape:
        tls:
          ca_cert: "((prom_scraper_scrape_tls.ca))"
          cert: "((prom_scraper_scrape_tls.certificate))"
          key: "((prom_scraper_scrape_tls.private_key))"

- type: replace
  path: /releases/name=metrics-discovery?
  value:
    name: metrics-discovery
    version: latest

- type: replace
  path: /variables/name=prom_scraper_scrape_tls?
  value:
    name: prom_scraper_scrape_tls
    type: certificate
    options:
      ca: metric_scraper_ca
      common_name: prom_scraper
      extended_key_usage:
      - client_auth
