- type: replace
  path: /addons/name=metrics-agent?
  value:
    name: metrics-agent
    include:
      stemcell:
      - os: ubuntu-xenial
    exclude:
      jobs:
      - name: smoke_tests
        release: cf-smoke-tests
    jobs:
    - name: metrics-agent
      release: metrics-discovery
      properties:
        grpc:
          ca_cert: "((loggregator_tls_agent.ca))"
          cert: "((loggregator_tls_agent.certificate))"
          key: "((loggregator_tls_agent.private_key))"
        metrics:
          ca_cert: "((metrics_agent_tls.ca))"
          cert: "((metrics_agent_tls.certificate))"
          key: "((metrics_agent_tls.private_key))"
          server_name: metrics_agent
        scrape:
          tls:
            ca_cert: "((prom_scraper_scrape_tls.ca))"
            cert: "((prom_scraper_scrape_tls.certificate))"
            key: "((prom_scraper_scrape_tls.private_key))"

- type: replace
  path: /variables/name=metric_scraper_ca?
  value:
    name: metric_scraper_ca
    type: certificate
    options:
      is_ca: true
      common_name: metricScraperCA

- type: replace
  path: /variables/name=metrics_agent_tls?
  value:
    name: metrics_agent_tls
    type: certificate
    options:
      ca: metric_scraper_ca
      common_name: metrics_agent
      extended_key_usage:
      - server_auth

- type: replace
  path: /releases/name=metrics-discovery?
  value:
    name: metrics-discovery
    version: latest

- type: replace
  path: /variables/name=prom_scraper_scrape_tls?
  value:
    name: prom_scraper_scrape_tls
    type: certificate
    options:
      ca: metric_scraper_ca
      common_name: prom_scraper
      extended_key_usage:
      - client_auth
