resource_types:
- name: pcf-pool
  source:
    repository: cftoolsmiths/toolsmiths-envs-resource
  type: docker-image

resources:
- name: cf-env
  type: pcf-pool
  source:
    api_token: ((toolsmith-api-key))
    hostname: environments.toolsmiths.cf-app.com
    pool_name: cf-deployment
  tags:
  - cf-denver-shared-vsphere

# - name: golang-release
#   type: git
#   source:
#     branch: master
#     uri: git@github.com:bosh-packages/golang-release
#     tag_filter: v*
#     private_key: ((cf-loggregator-oauth-bot-key))

- name: 24h
  source:
    interval: 24h
  type: time

- name: cf-acceptance-tests
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-acceptance-tests.git
  type: git

- name: cf-deployment
  source:
    branch: master
    private_key: ((cf-loggregator-oauth-bot-key))
    uri: https://github.com/cloudfoundry/cf-deployment
  type: git

- name: cf-deployment-concourse-tasks
  source:
    tag_filter: v*
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks
  type: git

- name: cf-deployment-concourse-tasks-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: latest
  type: docker-image

- name: cf-drain-cli
  source:
    branch: develop
    uri: https://github.com/cloudfoundry/cf-drain-cli
  type: git

- name: concourse-tasks
  source:
    branch: master
    uri: https://github.com/pivotal-cf/concourse-tasks
  type: git

- name: loggregator-ci
  source:
    branch: master
    private_key: ((cf-loggregator-oauth-bot-key))
    uri: git@github.com:cloudfoundry/loggregator-ci
  type: git

- name: metrics-discovery-release
  source:
    branch: develop
    ignore_paths:
    - .final_builds
    - releases
    private_key: ((cf-loggregator-oauth-bot-key))
    uri: git@github.com:cloudfoundry/metrics-discovery-release.git
  type: git

- name: metrics-discovery-release-elect
  source:
    branch: release-elect
    ignore_paths:
    - .final_builds
    - releases
    private_key: ((cf-loggregator-oauth-bot-key))
    uri: git@github.com:cloudfoundry/metrics-discovery-release.git
  type: git

- name: metrics-discovery-release-master
  source:
    branch: master
    disable_ci_skip: true
    private_key: ((cf-loggregator-oauth-bot-key))
    uri: git@github.com:cloudfoundry/metrics-discovery-release.git
  type: git

- name: nats-release
  source:
    branch: release
    private_key: ((cf-loggregator-oauth-bot-key))
    uri: git@github.com:cloudfoundry/nats-release.git
  type: git

jobs:
################################################################################################################
#                                                Dependencies
################################################################################################################
# - name: bump-dependencies
# - name: bump-golang-release


################################################################################################################
#                                              Unit Tests
################################################################################################################
- name: metrics-discovery-tests
  plan:
  - in_parallel:
    - get: loggregator-ci
    - get: 24h
      trigger: true
    - get: metrics-discovery-release
      trigger: true
  - in_parallel:
    - file: loggregator-ci/tasks/go-test/task.yml
      input_mapping:
        source-repo: metrics-discovery-release
      task: run-tests
    - do:
      - file: loggregator-ci/tasks/go-windows-tests/build-binary/task.yml
        input_mapping:
          release: metrics-discovery-release
        task: build-windows-test-binary
      - file: loggregator-ci/tasks/go-windows-tests/run-tests/task.yml
        task: run-windows-tests
  serial: true


################################################################################################################
#                                              CLAIM ENV AND DEPLOY
################################################################################################################
- name: claim-cfd
  plan:
  - get: metrics-discovery-release
    passed: ["metrics-discovery-tests"]
    trigger: true
  - put: cf-env
    tags:
    - cf-denver-shared-vsphere
    params:
      action: claim

- name: cf-deploy
  plan:
  - in_parallel:
    - get: loggregator-ci
    - get: cf-env
      passed: [claim-cfd]
      trigger: true
      tags:
      - cf-denver-shared-vsphere
    - get: cf-deployment
      trigger: true
    - get: cf-deployment-concourse-tasks
    - get: metrics-discovery-release
      passed:
      - metrics-discovery-tests
      trigger: true
    - get: cf-drain-cli
    - get: nats-release
  - task: grab-cf-manifest
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
          tag: latest
      inputs:
      - name: cf-env
      - name: cf-deployment
      outputs:
      - name: generated-cf-deployment
      run:
        path: /bin/bash
        args:
        - -c
        - |
          set -eo pipefail
          eval "$(bbl print-env --metadata-file cf-env/metadata)"

          echo "Grab CF manifest"
          bosh -d cf manifest > generated-cf-deployment/cf-tmp.yml

          echo "Delete CF deployment"
          bosh delete-deployment -d cf -n

          echo "Clean up releases"
          bosh clean-up --all -n

          echo "Update CF manifest with Windows ops-files"
          bosh int generated-cf-deployment/cf-tmp.yml \
          -o cf-deployment/operations/use-latest-stemcell.yml \
          -o cf-deployment/operations/use-latest-windows2019-stemcell.yml \
          -o cf-deployment/operations/windows2019-cell.yml \
          # -o cf-deployment/operations/use-compiled-releases.yml \
          # -o cf-deployment/operations/experimental/use-compiled-releases-windows.yml \
          -o cf-deployment/operations/experimental/use-online-windows2019fs.yml > generated-cf-deplyment/cf-deployment.yml

  - task: deploy-metrics-discovery
    file: cf-deployment-concourse-tasks/bosh-deploy-with-created-release/task.yml
    input_mapping:
      release: metrics-discovery-release
      toolsmiths-env: cf-env
      ops-files: metrics-discovery-release
      vars-files: generated-cf-deployment
    params:
      # manifests/operations/cf-add-metrics-discovery-windows.yml
      OPS_FILES: |
        manifests/operations/cf-add-metrics-discovery.yml


################################################################################################################
#                                      INTEGRATION TESTS
################################################################################################################
- name: test-releases-can-be-exported
  plan:
  - in_parallel:
    - get: concourse-tasks
    - get: cf-deployment-concourse-tasks-image
    - get: cf-env
      passed: [cf-deploy]
      tags:
      - cf-denver-shared-vsphere
    - get: metrics-discovery-release
      passed:
      - cf-deploy
      trigger: true
  - do:
    - file: concourse-tasks/release/export/task.yml
      input_mapping:
        cfd-env: cf-env
      params:
        RELEASE_NAMES: |
          metrics-discovery
      task: export-releases-xenial
    - file: concourse-tasks/release/export/task.yml
      input_mapping:
        cfd-env: cf-env
      params:
        RELEASE_NAMES: |
          metrics-discovery
        STEMCELL_OS: windows2019
      task: export-releases-windows2019
  serial: true
  serial_groups:
  - bosh-export-releases

- name: test-metrics-agent
  plan:
  - in_parallel:
    - get: loggregator-ci
    - get: cf-env
      passed: [cf-deploy]
      tags:
      - cf-denver-shared-vsphere
    - get: metrics-discovery-release
      passed:
      - cf-deploy
      trigger: true
  - file: loggregator-ci/tasks/test-metrics-agent/task.yml
    params:
      METRICS_AGENT_PORT: 14726
    task: test-metrics-agent
  serial: true
  serial_groups:
  - bosh-metrics-agent

- name: cats
  plan:
  - in_parallel:
    - get: cf-deployment-concourse-tasks
    - get: cf-env
      passed: [cf-deploy]
      tags:
      - cf-denver-shared-vsphere
    - get: loggregator-ci
    - get: cf-acceptance-tests
    - get: metrics-discovery-release
      passed:
      - cf-deploy
      trigger: true
  - task: generate-config
    file: cf-deployment-concourse-tasks/update-integration-configs/task.yml
    input_mapping:
      toolsmiths-env: cf-env
      integration-configs: loggregator-ci
    params:
      CATS_INTEGRATION_CONFIG_FILE: cats-config.json
  - file: cf-deployment-concourse-tasks/run-cats/task.yml
    input_mapping:
      cf-acceptance-tests: cf-acceptance-tests
      integration-config: updated-integration-configs
    params:
      NODES: 9
      CONFIG_FILE_PATH: cats-config.json
    task: run-cats
  serial: true
  serial_groups:
  - bosh-cf-cats

- name: unclaim-cfd
  plan:
  - get: cf-env
    passed:
    - cats
    - test-metrics-agent
    - test-releases-can-be-exported
    trigger: true
    tags:
    - cf-denver-shared-vsphere
  - put: cf-env
    tags:
    - cf-denver-shared-vsphere
    params:
      env_file: cf-env/metadata
      action: unclaim


- name: metrics-discovery-promotion
  plan:
  - in_parallel:
    - get: develop
      passed:
      - cats
      - test-metrics-agent
      - test-releases-can-be-exported
      resource: metrics-discovery-release
      trigger: true
    - get: metrics-discovery-release-elect
  - params:
      repository: develop
    put: metrics-discovery-release-elect
  serial: true
- name: metrics-discovery-master-promotion
  plan:
  - in_parallel:
    - get: 24h
      trigger: true
    - get: metrics-discovery-release-elect
      passed:
      - metrics-discovery-promotion
      trigger: true
    - get: metrics-discovery-release-master
    - get: loggregator-ci
  - file: loggregator-ci/tasks/bumper/task.yml
    input_mapping:
      dest: metrics-discovery-release-master
      source: metrics-discovery-release-elect
    params:
      DEST_BRANCH: master
      SOURCE_BRANCH: release-elect
      TRACKER_API_TOKEN: 9a8e6bb0f9edf884e3880a540de40ad4
    task: bumper
  - params:
      repository: merged-dest
    put: metrics-discovery-release-master

################################################################################################################
#                                               Cut Releases
################################################################################################################
# - name: create-release-patch
# - name: create-release-minor
# - name: create-release-major
